apply plugin: 'com.android.application'

android {

    namespace 'lib.kalu.tool'
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {

        minSdkVersion 23
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }

        //添加此行
        flavorDimensions "default"
    }

    signingConfigs {
        release {
            storeFile file("debug.jks")
            storePassword "123456"
            keyAlias "debug"
            keyPassword "123456"
            v1SigningEnabled true
            v2SigningEnabled true
        }
        debug {
            storeFile file("debug.jks")
            storePassword "123456"
            keyAlias "debug"
            keyPassword "123456"
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
        }
        debug {
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    sourceSets.main {
        jni.srcDirs = []
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {

    // opensslKit
    implementation project(':lib-openssl-kit')
    implementation(files("libs/lib_opensslkit_release_20250623.aar"))

    // 模块依赖
//    implementation project(':lib_safetools_jni')
//    implementation project(':lib_safetools_java')

    implementation('androidx.appcompat:appcompat:1.6.1')
}